## Feature Scaling - Normalization and standardization

In [2]:
import pandas as pd

In [3]:
data = {
    'Age': [25, 40, 65, 30, 55],
    'Salary': [50000, 80000, 150000, 60000, 120000]
}

df = pd.DataFrame(data)
df

   Age  Salary
0   25   50000
1   40   80000
2   65  150000
3   30   60000
4   55  120000

# Normalization
- calculate min and max value of particular column
- norm = (value - min) / (max - min)

In [5]:
age_min = df['Age'].min()
age_max = df['Age'].max()
age_min, age_max

(np.int64(25), np.int64(65))

In [ ]:
# Normalzied age column
df['Age_norm'] = (df['Age'] - age_min) / (age_max - age_min)
df
# min value is 0 and max value is 1, all the other values comes in between 0 and 1

   Age  Salary  Age_norm
0   25   50000     0.000
1   40   80000     0.375
2   65  150000     1.000
3   30   60000     0.125
4   55  120000     0.750

In [7]:
# Normalized Salary column
salary_min = df['Salary'].min()
salary_max = df['Salary'].max()
df['Salary_norm'] = (df['Salary']-salary_min) / (salary_max - salary_min)
df

   Age  Salary  Age_norm  Salary_norm
0   25   50000     0.000          0.0
1   40   80000     0.375          0.3
2   65  150000     1.000          1.0
3   30   60000     0.125          0.1
4   55  120000     0.750          0.7

In [8]:
! pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp311-cp311-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.19.5 in d:\anoconda\envs\tech-axis\lib\site-packages (from scikit-learn) (2.2.4)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.15.2-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.1-cp311-cp311-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 699.0 kB/s eta 0:00:16
   - -------------------------------------- 0.5/11.1 MB 699.0 kB/s eta 0:00:16
   - -------------------------------------- 0.5/11.1 MB 699.0 kB/s eta 0:00:16
   -- ------------------------------------- 0.8/11.1 MB 532.8 kB/s eta 0:00:20
   --- ------------------------------------ 1.0/11.1 MB 671.0 kB/s eta 0:00:16
   --- ------------------------------------ 1.0/11.1 MB 671.0 kB/s eta 0:00:16
   --- ------------------------------------ 1.0/11.1 MB 671.0 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/11.1 MB 536.9 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/11.1 MB 536.9 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/11.1 MB 536.9 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/11.1 MB 536.9 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/11.1 MB 536.9 kB/s eta 0:00:19
   ----- ---------------------------------- 1.6/11.1 MB 432.4 kB/s eta 0:00:23
   ----- ---------------------------------- 1.6/11.1 MB 432.4 kB/s eta 0:00:23
   ----- ---------------------------------- 1.6/11.1 MB 432.4 kB/s eta 0:00:23
   ----- ---------------------------------- 1.6/11.1 MB 432.4 kB/s eta 0:00:23
   ------ --------------------------------- 1.8/11.1 MB 405.9 kB/s eta 0:00:23
   ------ --------------------------------- 1.8/11.1 MB 405.9 kB/s eta 0:00:23
   ------ --------------------------------- 1.8/11.1 MB 405.9 kB/s eta 0:00:23
   ------ --------------------------------- 1.8/11.1 MB 405.9 kB/s eta 0:00:23
   ------ --------------------------------- 1.8/11.1 MB 405.9 kB/s eta 0:00:23
   ------ --------------------------------- 1.8/11.1 MB 405.9 kB/s eta 0:00:23
   ------ --------------------------------- 1.8/11.1 MB 405.9 kB/s eta 0:00:23
   ------- -------------------------------- 2.1/11.1 MB 348.5 kB/s eta 0:00:26
   ------- -------------------------------- 2.1/11.1 MB 348.5 kB/s eta 0:00:26
   ------- -------------------------------- 2.1/11.1 MB 348.5 kB/s eta 0:00:26
   ------- -------------------------------- 2.1/11.1 MB 348.5 kB/s eta 0:00:26
   -------- ------------------------------- 2.4/11.1 MB 335.5 kB/s eta 0:00:27
   -------- ------------------------------- 2.4/11.1 MB 335.5 kB/s eta 0:00:27
   -------- ------------------------------- 2.4/11.1 MB 335.5 kB/s eta 0:00:27
   --------- ------------------------------ 2.6/11.1 MB 344.8 kB/s eta 0:00:25
   --------- ------------------------------ 2.6/11.1 MB 344.8 kB/s eta 0:00:25
   ---------- ----------------------------- 2.9/11.1 MB 358.5 kB/s eta 0:00:24
   ---------- ----------------------------- 2.9/11.1 MB 358.5 kB/s eta 0:00:24
   ----------- ---------------------------- 3.1/11.1 MB 375.9 kB/s eta 0:00:22
   ----------- ---------------------------- 3.1/11.1 MB 375.9 kB/s eta 0:00:22
   ------------ --------------------------- 3.4/11.1 MB 391.7 kB/s eta 0:00:20
   ------------- -------------------------- 3.7/11.1 MB 407.7 kB/s eta 0:00:19
   ------------- -------------------------- 3.7/11.1 MB 407.7 kB/s eta 0:00:19
   -------------- ------------------------- 3.9/11.1 MB 424.8 kB/s eta 0:00:17
   --------------- ------------------------ 4.2/11.1 MB 441.5 kB/s eta 0:00:16
   ---------------- ----------------------- 4.5/11.1 MB 453.4 kB/s eta 0:00:15
   ---------------- ----------------------- 4.5/11.1 MB 453.4 kB/s eta 0:00:15
   ---------------- ----------------------- 4.7/11.1 MB 465.3 kB/s eta 0:00:14
   ---------------- ----------------------- 4.7/11.1 MB 465.3 kB/s eta 0:00:14
   ----------------- ---------------------- 5.0/11.1 MB 476.3 kB/s eta 0:00:13
   ------------------ --------------------- 5.2/11.1 MB 488.2 kB/s eta 0:00:13
   ------------------- -------------------- 5.5/11.1 MB 499.3 kB/s eta 0:00:12
   ------------------- -------------------- 5.5/11.1 MB 499.3 kB/s eta 0:00:12
   -------------------- ------------------- 5.8/11.1 MB 510.6 kB/s eta 0:00:11
   --------------------- ------------------ 6.0/11.1 MB 523.6 kB/s eta 0:00:10
   ---------------------- ----------------- 6.3/11.1 MB 535.2 kB/s eta 0:00:10
   ----------------------- ---------------- 6.6/11.1 MB 546.4 kB/s eta 0:00:09
   ------------------------ --------------- 6.8/11.1 MB 560.8 kB/s eta 0:00:08
   -------------------------- ------------- 7.3/11.1 MB 587.5 kB/s eta 0:00:07
   --------------------------- ------------ 7.6/11.1 MB 600.0 kB/s eta 0:00:06
   ---------------------------- ----------- 7.9/11.1 MB 615.1 kB/s eta 0:00:06
   ----------------------------- ---------- 8.1/11.1 MB 622.2 kB/s eta 0:00:05
   ------------------------------- -------- 8.7/11.1 MB 650.8 kB/s eta 0:00:04
   -------------------------------- ------- 8.9/11.1 MB 663.9 kB/s eta 0:00:04
   --------------------------------- ------ 9.4/11.1 MB 693.3 kB/s eta 0:00:03
   ----------------------------------- ---- 10.0/11.1 MB 720.2 kB/s eta 0:00:02
   ------------------------------------- -- 10.5/11.1 MB 748.7 kB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 781.3 kB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.15.2-cp311-cp311-win_amd64.whl (41.2 MB)
   ---------------------------------------- 0.0/41.2 MB ? eta -:--:--
    --------------------------------------- 0.8/41.2 MB 3.7 MB/s eta 0:00:11
   - -------------------------------------- 1.6/41.2 MB 3.8 MB/s eta 0:00:11
   -- ------------------------------------- 2.4/41.2 MB 3.9 MB/s eta 0:00:10
   --- ------------------------------------ 3.1/41.2 MB 4.1 MB/s eta 0:00:10
   --- ------------------------------------ 3.9/41.2 MB 3.9 MB/s eta 0:00:10
   ---- ----------------------------------- 5.0/41.2 MB 3.9 MB/s eta 0:00:10
   ------ --------------------------------- 6.3/41.2 MB 4.2 MB/s eta 0:00:09
   ------- -------------------------------- 7.3/41.2 MB 4.3 MB/s eta 0:00:08
   ------- -------------------------------- 8.1/41.2 MB 4.3 MB/s eta 0:00:08
   -------- ------------------------------- 9.2/41.2 MB 4.3 MB/s eta 0:00:08
   --------- ------------------------------ 9.7/41.2 MB 4.2 MB/s eta 0:00:08
   ---------- ----------------------------- 10.5/41.2 MB 4.1 MB/s eta 0:00:08
   ----------- ---------------------------- 11.5/41.2 MB 4.1 MB/s eta 0:00:08
   ------------ --------------------------- 12.6/41.2 MB 4.2 MB/s eta 0:00:07
   ------------- -------------------------- 13.6/41.2 MB 4.2 MB/s eta 0:00:07
   -------------- ------------------------- 14.7/41.2 MB 4.3 MB/s eta 0:00:07
   --------------- ------------------------ 15.7/41.2 MB 4.3 MB/s eta 0:00:06
   ---------------- ----------------------- 17.0/41.2 MB 4.4 MB/s eta 0:00:06
   ----------------- ---------------------- 18.1/41.2 MB 4.5 MB/s eta 0:00:06
   ------------------ --------------------- 19.1/41.2 MB 4.4 MB/s eta 0:00:05
   ------------------- -------------------- 20.4/41.2 MB 4.5 MB/s eta 0:00:05
   -------------------- ------------------- 21.5/41.2 MB 4.6 MB/s eta 0:00:05
   --------------------- ------------------ 22.5/41.2 MB 4.6 MB/s eta 0:00:05
   ---------------------- ----------------- 23.3/41.2 MB 4.6 MB/s eta 0:00:04
   ----------------------- ---------------- 24.6/41.2 MB 4.6 MB/s eta 0:00:04
   ------------------------ --------------- 25.4/41.2 MB 4.6 MB/s eta 0:00:04
   ------------------------- -------------- 26.2/41.2 MB 4.6 MB/s eta 0:00:04
   -------------------------- ------------- 27.3/41.2 MB 4.6 MB/s eta 0:00:04
   --------------------------- ------------ 28.0/41.2 MB 4.5 MB/s eta 0:00:03
   --------------------------- ------------ 28.6/41.2 MB 4.5 MB/s eta 0:00:03
   ---------------------------- ----------- 29.1/41.2 MB 4.4 MB/s eta 0:00:03
   ---------------------------- ----------- 29.6/41.2 MB 4.4 MB/s eta 0:00:03
   ----------------------------- ---------- 30.4/41.2 MB 4.3 MB/s eta 0:00:03
   ------------------------------ --------- 31.2/41.2 MB 4.3 MB/s eta 0:00:03
   ------------------------------- -------- 32.0/41.2 MB 4.2 MB/s eta 0:00:03
   ------------------------------- -------- 32.5/41.2 MB 4.2 MB/s eta 0:00:03
   -------------------------------- ------- 33.3/41.2 MB 4.2 MB/s eta 0:00:02
   -------------------------------- ------- 33.8/41.2 MB 4.2 MB/s eta 0:00:02
   --------------------------------- ------ 34.3/41.2 MB 4.1 MB/s eta 0:00:02
   --------------------------------- ------ 34.6/41.2 MB 4.0 MB/s eta 0:00:02
   ---------------------------------- ----- 35.1/41.2 MB 4.0 MB/s eta 0:00:02
   ---------------------------------- ----- 35.4/41.2 MB 4.0 MB/s eta 0:00:02
   ----------------------------------- ---- 36.2/41.2 MB 3.9 MB/s eta 0:00:02
   ----------------------------------- ---- 36.7/41.2 MB 3.9 MB/s eta 0:00:02
   ------------------------------------ --- 37.2/41.2 MB 3.9 MB/s eta 0:00:02
   ------------------------------------ --- 37.7/41.2 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 38.3/41.2 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 38.8/41.2 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 39.3/41.2 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 39.6/41.2 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 40.1/41.2 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  40.4/41.2 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  40.6/41.2 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  40.6/41.2 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  40.9/41.2 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 41.2/41.2 MB 3.4 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.2 threadpoolctl-3.6.0

In [9]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['Age_norm_sk', 'Salary_norm_sk']] = scaler.fit_transform(df[['Age', 'Salary']])
df

   Age  Salary  Age_norm  Salary_norm  Age_norm_sk  Salary_norm_sk
0   25   50000     0.000          0.0        0.000             0.0
1   40   80000     0.375          0.3        0.375             0.3
2   65  150000     1.000          1.0        1.000             1.0
3   30   60000     0.125          0.1        0.125             0.1
4   55  120000     0.750          0.7        0.750             0.7

## Standardization
norm = (value - mean) / std

In [11]:
# age stan
data = {
    'Age': [25, 40, 65, 30, 55],
    'Salary': [50000, 80000, 150000, 60000, 120000]
}

df = pd.DataFrame(data)
df

   Age  Salary
0   25   50000
1   40   80000
2   65  150000
3   30   60000
4   55  120000

In [ ]:
age_mean = df['Age'].mean()
age_std = df['Age'].std()

df['Age_std'] = (df['Age'] - age_mean) / age_std
df

   Age  Salary   Age_std
0   25   50000 -1.070935
1   40   80000 -0.178489
2   65  150000  1.308921
3   30   60000 -0.773453
4   55  120000  0.713957

In [15]:
age_mean, df['Age_std'].mean()

(np.float64(43.0), np.float64(0.0))

In [17]:
salary_mean = df['Salary'].mean()
salary_std = df['Salary'].std()

df['Salary_std'] = (df['Salary'] - salary_mean) / salary_std
df

   Age  Salary   Age_std  Salary_std
0   25   50000 -1.070935   -0.998304
1   40   80000 -0.178489   -0.285230
2   65  150000  1.308921    1.378610
3   30   60000 -0.773453   -0.760612
4   55  120000  0.713957    0.665536

In [20]:
df['Salary'].mean(), df['Salary_std'].mean()

(np.float64(92000.0), np.float64(-2.2204460492503132e-17))

In [23]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
df[['Age_std_sk', 'Salary_std_sk']] = std_scaler.fit_transform(df[['Age', 'Salary']])
df

   Age  Salary   Age_std  Salary_std  Age_std_sk  Salary_std_sk
0   25   50000 -1.070935   -0.998304   -1.197342      -1.116137
1   40   80000 -0.178489   -0.285230   -0.199557      -0.318896
2   65  150000  1.308921    1.378610    1.463418       1.541333
3   30   60000 -0.773453   -0.760612   -0.864747      -0.850390
4   55  120000  0.713957    0.665536    0.798228       0.744092

In [ ]:
# Skew